services:
  - type: web
    name: youtube-channel-finder
    env: ruby
    buildCommand: bundle install 
    startCommand: bundle exec rackup config.ru -p 4567 -o 0.0.0.0
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
    buildFilter:
      paths:
      - app.rb
      - Gemfile
      - Gemfile.lock
      - config.ru